Bundler/DuplicatedGem:
  Description: 'Checks for duplicate gem entries in Gemfile.'
  Enabled: true
  Include:
    - '**/Gemfile'
    - '**/gems.rb'

# Bundler/OrderedGems:
#   Description: >-
#                  Gems within groups in the Gemfile should be alphabetically sorted.
#   Enabled: true
#   Include:
#     - '**/Gemfile'
#     - '**/gems.rb'
