inherit_gem:
  omawari:
    - config/bundler.yml
    - config/lint.yml
    - config/performance.yml
    - config/security.yml
    - config/style.yml
    # uncomment if use rails cops
    # - config/rails.yml
    # uncomment if use rspec cops
    # - config/rspec.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: false
  DisabledByDefault: true
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*
  TargetRubyVersion: <%= RUBY_VERSION.split(".")[0..-2].join(".") %>
  # uncomment if use rails cops
  # TargetRailsVersion: 5.0

#################### Style #################################

# Style/CollectionMethods:
#   Description: 'Preferred collection methods.'
#   StyleGuide: '#map-find-select-reduce-size'
#   Enabled: false
#   PreferredMethods:
#     collect:  'map'
#     collect!: 'map!'
#     inject:   'inject'
#     detect:   'detect'
#     find_all: 'select'

# Style/DotPosition:
#   Description: 'Checks the position of the dot in multi-line method calls.'
#   StyleGuide: '#consistent-multi-line-chains'
#   Enabled: true
#   EnforcedStyle: leading
#   SupportedStyles:
#     - leading
#     - trailing

# Style/StringLiterals:
#   Description: 'Checks if uses of quotes match the configured preference.'
#   StyleGuide: '#consistent-string-literals'
#   Enabled: true
#   EnforcedStyle: single_quotes
#   SupportedStyles:
#     - single_quotes
#     - double_quotes
#   # If `true`, strings which span multiple lines using `\` for continuation must
#   # use the same type of quotes on each line.
#   ConsistentQuotesInMultiline: false

# Style/StringLiteralsInInterpolation:
#   EnforcedStyle: single_quotes
#   SupportedStyles:
#     - single_quotes
#     - double_quotes

# Style/NumericLiterals:
#   Description: >-
#                  Add underscores to large numeric literals to improve their
#                  readability.
#   StyleGuide: '#underscores-in-numerics'
#   Enabled: true

# Style/AlignParameters:
#   # Alignment of parameters in multi-line method calls.
#   #
#   # The `with_first_parameter` style aligns the following lines along the same
#   # column as the first parameter.
#   #
#   #     method_call(a,
#   #                 b)
#   #
#   # The `with_fixed_indentation` style aligns the following lines with one
#   # level of indentation relative to the start of the line with the method call.
#   #
#   #     method_call(a,
#   #       b)
#   EnforcedStyle: with_first_parameter
#   SupportedStyles:
#     - with_first_parameter
#     - with_fixed_indentation
#   # By default, the indentation width from Style/IndentationWidth is used
#   # But it can be overridden by setting this parameter
#   IndentationWidth: ~
#   Enabled: true

Style/PercentLiteralDelimiters:
  # Specify the default preferred delimiter for all types with the 'default' key
  # Override individual delimiters (even with default specified) by specifying
  # an individual key
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

#################### Metrics ###############################

# Metrics/AbcSize:
#   Description: >-
#                  A calculated magnitude based on number of assignments,
#                  branches, and conditions.
#   Reference: 'http://c2.com/cgi/wiki?AbcMetric'
#   Enabled: true
#   Max: 15

# Metrics/BlockLength:
#   Description: 'Avoid long blocks with many lines.'
#   Enabled: true
#   CountComments: false  # count full line comments?
#   Max: 25
#   ExcludedMethods: []

# Metrics/BlockNesting:
#   Description: 'Avoid excessive block nesting'
#   StyleGuide: '#three-is-the-number-thou-shalt-count'
#   Enabled: true
#   CountBlocks: false
#   Max: 3

# Metrics/ClassLength:
#   Description: 'Avoid classes longer than 100 lines of code.'
#   Enabled: true
#   CountComments: false  # count full line comments?
#   Max: 100

# Metrics/ModuleLength:
#   Description: 'Avoid modules longer than 100 lines of code.'
#   Enabled: true
#   CountComments: false  # count full line comments?
#   Max: 100

# Avoid complex methods.
# Metrics/CyclomaticComplexity:
#   Description: >-
#                  A complexity metric that is strongly correlated to the number
#                  of test cases needed to validate a method.
#   Enabled: true
#   Max: 6

# Metrics/LineLength:
#   Max: 80
#   # To make it possible to copy or click on URIs in the code, we allow lines
#   # containing a URI to be longer than Max.
#   AllowHeredoc: true
#   AllowURI: true
#   URISchemes:
#     - http
#     - https
#   # The IgnoreCopDirectives option causes the LineLength rule to ignore cop
#   # directives like '# rubocop: enable ...' when calculating a line's length.
#   IgnoreCopDirectives: false
#   # The IgnoredPatterns option is a list of !ruby/regexp and/or string
#   # elements. Strings will be converted to Regexp objects. A line that matches
#   # any regular expression listed in this option will be ignored by LineLength.
#   IgnoredPatterns: []
#   Description: 'Limit lines to 80 characters.'
#   StyleGuide: '#80-character-limits'
#   Enabled: true

# Metrics/MethodLength:
#   Description: 'Avoid methods longer than 10 lines of code.'
#   StyleGuide: '#short-methods'
#   Enabled: true
#   CountComments: false  # count full line comments?
#   Max: 10

# Metrics/ParameterLists:
#   Description: 'Avoid parameter lists longer than three or four parameters.'
#   StyleGuide: '#too-many-params'
#   Enabled: true
#   Max: 5
#   CountKeywordArgs: true

# Metrics/PerceivedComplexity:
#   Description: >-
#                  A complexity metric geared towards measuring complexity for a
#                  human reader.
#   Enabled: true
#   Max: 7
